// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjp6v7654L-fc1NXt4Q0Ksntoml5Eohas',
    appId: '1:225969486095:web:6db7601e227be5c2afa67a',
    messagingSenderId: '225969486095',
    projectId: 'vayu-c00f8',
    authDomain: 'vayu-c00f8.firebaseapp.com',
    databaseURL: 'https://vayu-c00f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vayu-c00f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPVrfUhM3tHaERG9ae57ob79ZqWtBaFgY',
    appId: '1:225969486095:android:47776f190387a86cafa67a',
    messagingSenderId: '225969486095',
    projectId: 'vayu-c00f8',
    databaseURL: 'https://vayu-c00f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vayu-c00f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGbI6bmYi__q6bHId1MkvjLecu1e0jwvM',
    appId: '1:225969486095:ios:6099a03245fdac1aafa67a',
    messagingSenderId: '225969486095',
    projectId: 'vayu-c00f8',
    databaseURL: 'https://vayu-c00f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vayu-c00f8.appspot.com',
    androidClientId: '225969486095-n6rumckpbhroo2dvcgifboj50rh184d1.apps.googleusercontent.com',
    iosClientId: '225969486095-fp528j09ckjeoptfta0bj8qm7d0hsr4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.vayuFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGbI6bmYi__q6bHId1MkvjLecu1e0jwvM',
    appId: '1:225969486095:ios:24560d9f4cb2b290afa67a',
    messagingSenderId: '225969486095',
    projectId: 'vayu-c00f8',
    databaseURL: 'https://vayu-c00f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vayu-c00f8.appspot.com',
    androidClientId: '225969486095-n6rumckpbhroo2dvcgifboj50rh184d1.apps.googleusercontent.com',
    iosClientId: '225969486095-rsae49dpv73p9ft50pdi78fb7ht95b2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.vayuFlutterApp.RunnerTests',
  );
}
